apiVersion: v1
kind: ConfigMap
metadata:
  name: pangolin-config
data:
  app:
    dashboard_url: "https://proxy.cooperfle.com"
    log_level: "info"
    save_logs: false

  domains:
    cooperfle:
      base_domain: "cooperfle.com"
      cert_resolver: "letsencrypt"
      prefer_wildcard_cert: true
    cooperbike:
      base_domain: "cooper.bike"
      cert_resolver: "letsencrypt"
      prefer_wildcard_cert: true

  server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: "pangolin"
    session_cookie_name: "p_session_token"
    resource_access_token_param: "p_token"
    resource_session_request_param: "p_session_request"

  traefik:
    cert_resolver: "letsencrypt"
    http_entrypoint: "web"
    https_entrypoint: "websecure"

  gerbil:
    start_port: 51820
    base_endpoint: "example.com"
    use_subdomain: false
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.137.0/20

  rate_limits:
    global:
      window_minutes: 1
      max_requests: 100

  users:
    server_admin:
      email: "h8vtlbktb@mozmail.com"
      password: "_VBMMgGK*TmQF43F3TvrA"

  flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: true
    allow_raw_resources: true
    allow_base_domain_resources: true
