apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: newt
  name: newt
  namespace: cooperfle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: newt
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: newt
    spec:
      containers:
        - env:
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt-secrets
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt-secrets
                  key: NEWT_SECRET
            - name: PANGOLIN_ENDPOINT
              value: https://proxy.cooperfle.com
          image: fosrl/newt
          name: newt
      restartPolicy: Always
